###

POST http://localhost:3000/users/
Content-Type: application/json

{   
    "name":"maneesh",
    "username":"maneesh@2024",
    "password": "maneesh",
    "gender": "Male",
    "location":"hyderabad"
}


###

POST http://localhost:3000/login/
Content-Type: application/json

{
    "username":"maneesh@2024",
    "password": "maneesh"
}